name: C/C++ CI

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0
            
    - uses: actions/checkout@v3
    - name: make
      run: make
